### ISSUE TITLE
change archive page (products-all)

### ISSUE THREAD

**Issue by amandablum** [wpshopify/wp-shopify#71]
How would you implement a theme based override template for website.com/products (the product archive) that currently uses   ##products-all.php?  wps-product-sidebar is alluded to in the files, but isn't in the list of hooks or calls. Is this a sidebar we can create or merely how you display the cart widget?  Namely want to install the bootstrap modal on the archive page (to create a quick shop) and add some styles and a sidebar. These are reasonably necessary items for the full use of the plugin. Similar systems are employed by woo, wpec, etc.

**Comment by arobbins** [comment]
Done and to be released in 1.0.49.
