### ISSUE TITLE
Plugin still being supported?

### ISSUE THREAD

**Issue by jamesgillispie** [wpshopify/wp-shopify#79]

**Comment by arobbins** [comment]
@jamesgillispie Absolutely! 

I've been working on a major syncing upgrade for the past month or so. Should be releasing it this week.

**Comment by jamesgillispie** [comment]
@arobbins excellent thanks for update! Just so you know on your docs this appears 
<img width="290" alt="screen shot 2018-07-09 at 1 14 12 pm" src="https://user-images.githubusercontent.com/4491942/42465472-0e6196e4-837a-11e8-9f96-595c2836db1d.png">
