### ISSUE TITLE
Template Overriding Appears To Be Disabled

### ISSUE THREAD

**Issue by amilham** [wpshopify/wp-shopify#98]
On line 86 of `classes/class-template-loader.php`, the theme template override path is skipped over and templates are only found in the plugin's directory. Is there a reason for this?

**Comment by arobbins** [comment]
Hey @amilham ,

Thanks for the question. This repo only contains code for the free version. The reason `classes/class-template-loader.php` skips over the theme dir is because that code is only available in the pro version.

**Comment by amilham** [comment]
Ah, I had missed that that was a Pro feature.
